//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.07 at 01:41:53 PM EDT 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContactPointSystem-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContactPointSystem-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="phone"/>
 *     &lt;enumeration value="fax"/>
 *     &lt;enumeration value="email"/>
 *     &lt;enumeration value="url"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ContactPointSystem-list")
@XmlEnum
public enum ContactPointSystemList {


    /**
     * The value is a telephone number used for voice
     * 						calls. Use of full international numbers starting with + is
     * 						recommended to enable automatic dialing support but not required.
     * 					
     * 
     */
    @XmlEnumValue("phone")
    PHONE("phone"),

    /**
     * The value is a fax machine. Use of full
     * 						international numbers starting with + is recommended to enable
     * 						automatic dialing support but not required.
     * 					
     * 
     */
    @XmlEnumValue("fax")
    FAX("fax"),

    /**
     * The value is an email address.
     * 
     */
    @XmlEnumValue("email")
    EMAIL("email"),

    /**
     * The value is a url. This is intended for various
     * 						personal contacts including blogs, Twitter, Facebook, etc. Do not
     * 						use for email addresses.
     * 					
     * 
     */
    @XmlEnumValue("url")
    URL("url");
    private final java.lang.String value;

    ContactPointSystemList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ContactPointSystemList fromValue(java.lang.String v) {
        for (ContactPointSystemList c: ContactPointSystemList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
