//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.07 at 01:41:53 PM EDT 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContactPointUse-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContactPointUse-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="home"/>
 *     &lt;enumeration value="work"/>
 *     &lt;enumeration value="temp"/>
 *     &lt;enumeration value="old"/>
 *     &lt;enumeration value="mobile"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ContactPointUse-list")
@XmlEnum
public enum ContactPointUseList {


    /**
     * A communication contact point at a home;
     * 						attempted contacts for business purposes might intrude privacy and
     * 						chances are one will contact family or other household members
     * 						instead of the person one wishes to call. Typically used with
     * 						urgent cases, or if no other contacts are available.
     * 					
     * 
     */
    @XmlEnumValue("home")
    HOME("home"),

    /**
     * An office contact point. First choice for
     * 						business related contacts during business hours.
     * 					
     * 
     */
    @XmlEnumValue("work")
    WORK("work"),

    /**
     * A temporary contact point. The period can provide
     * 						more detailed information.
     * 					
     * 
     */
    @XmlEnumValue("temp")
    TEMP("temp"),

    /**
     * This contact point is no longer in use (or was
     * 						never correct, but retained for records).
     * 					
     * 
     */
    @XmlEnumValue("old")
    OLD("old"),

    /**
     * A telecommunication device that moves and stays
     * 						with its owner. May have characteristics of all other use codes,
     * 						suitable for urgent matters, not the first choice for routine
     * 						business.
     * 					
     * 
     */
    @XmlEnumValue("mobile")
    MOBILE("mobile");
    private final java.lang.String value;

    ContactPointUseList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ContactPointUseList fromValue(java.lang.String v) {
        for (ContactPointUseList c: ContactPointUseList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
