//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.07 at 01:41:53 PM EDT 
//


package org.hl7.fhir;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have a value for
 * 				at least one of the defined elements, an @id referenced from the
 * 				Narrative, or extensions
 * 			
 * 
 * <p>Java class for Element complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Element">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="extension" type="{http://hl7.org/fhir}Extension" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://hl7.org/fhir}id-primitive" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Element", propOrder = {
    "extension"
})
@XmlSeeAlso({
    Meta.class,
    Address.class,
    NameUse.class,
    AggregationMode.class,
    ElementDefinitionSlicing.class,
    EncounterClass.class,
    Coding.class,
    SampledData.class,
    Id.class,
    PositiveInt.class,
    ElementDefinition.class,
    EncounterState.class,
    Timing.class,
    ElementDefinitionBinding.class,
    DateTime.class,
    QuantityComparator.class,
    MessageEvent.class,
    Instant.class,
    ContactPoint.class,
    ElementDefinitionMapping.class,
    DataType.class,
    Ratio.class,
    Reference.class,
    ResourceType.class,
    IdentifierUse.class,
    Uri.class,
    AdministrativeGender.class,
    BackboneElement.class,
    QuestionnaireStatus.class,
    NoteType.class,
    BindingStrength.class,
    Date.class,
    EventTiming.class,
    ElementDefinitionConstraint.class,
    ConformanceResourceStatus.class,
    Attachment.class,
    Integer.class,
    ConstraintSeverity.class,
    Uuid.class,
    ParametersPart.class,
    Identifier.class,
    FHIRDefinedType.class,
    Narrative.class,
    ClinicalBaseGender.class,
    ContactPointSystem.class,
    Period.class,
    Range.class,
    DataAbsentReason.class,
    MaritalStatus.class,
    CompositionStatus.class,
    RemittanceOutcome.class,
    Base64Binary.class,
    SpecialValues.class,
    SampledDataDataType.class,
    Decimal.class,
    DocumentReferenceStatus.class,
    CodeableConcept.class,
    ConformanceUseContext.class,
    Code.class,
    org.hl7.fhir.String.class,
    PropertyRepresentation.class,
    Oid.class,
    NarrativeStatus.class,
    HumanName.class,
    AddressUse.class,
    TimingRepeat.class,
    ContactPointUse.class,
    ElementDefinitionType.class,
    Quantity.class,
    SearchParamType.class,
    UnitsOfTime.class,
    ParametersParameter.class,
    Extension.class,
    Boolean.class,
    Signature.class,
    UnsignedInt.class,
    SlicingRules.class,
    CompositionAttestationMode.class,
    Time.class
})
public class Element {

    protected List<Extension> extension;
    @XmlAttribute(name = "id")
    protected java.lang.String id;

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extension }
     * 
     * 
     */
    public List<Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<Extension>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
