//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.07 at 01:41:53 PM EDT 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have a value for
 * 				at least one of the defined elements, an @id referenced from the
 * 				Narrative, or extensions
 * 			
 * 
 * <p>Java class for ElementDefinition.Binding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElementDefinition.Binding">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}Element">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://hl7.org/fhir}string"/>
 *         &lt;element name="strength" type="{http://hl7.org/fhir}BindingStrength"/>
 *         &lt;element name="description" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="valueSetBoolean" type="{http://hl7.org/fhir}boolean"/>
 *           &lt;element name="valueSetInteger" type="{http://hl7.org/fhir}integer"/>
 *           &lt;element name="valueSetDecimal" type="{http://hl7.org/fhir}decimal"/>
 *           &lt;element name="valueSetBase64Binary" type="{http://hl7.org/fhir}base64Binary"/>
 *           &lt;element name="valueSetInstant" type="{http://hl7.org/fhir}instant"/>
 *           &lt;element name="valueSetString" type="{http://hl7.org/fhir}string"/>
 *           &lt;element name="valueSetUri" type="{http://hl7.org/fhir}uri"/>
 *           &lt;element name="valueSetDate" type="{http://hl7.org/fhir}date"/>
 *           &lt;element name="valueSetDateTime" type="{http://hl7.org/fhir}dateTime"/>
 *           &lt;element name="valueSetTime" type="{http://hl7.org/fhir}time"/>
 *           &lt;element name="valueSetCode" type="{http://hl7.org/fhir}code"/>
 *           &lt;element name="valueSetOid" type="{http://hl7.org/fhir}oid"/>
 *           &lt;element name="valueSetUuid" type="{http://hl7.org/fhir}uuid"/>
 *           &lt;element name="valueSetId" type="{http://hl7.org/fhir}id"/>
 *           &lt;element name="valueSetUnsignedInt" type="{http://hl7.org/fhir}unsignedInt"/>
 *           &lt;element name="valueSetPositiveInt" type="{http://hl7.org/fhir}positiveInt"/>
 *           &lt;element name="valueSetAttachment" type="{http://hl7.org/fhir}Attachment"/>
 *           &lt;element name="valueSetIdentifier" type="{http://hl7.org/fhir}Identifier"/>
 *           &lt;element name="valueSetCodeableConcept" type="{http://hl7.org/fhir}CodeableConcept"/>
 *           &lt;element name="valueSetCoding" type="{http://hl7.org/fhir}Coding"/>
 *           &lt;element name="valueSetQuantity" type="{http://hl7.org/fhir}Quantity"/>
 *           &lt;element name="valueSetRange" type="{http://hl7.org/fhir}Range"/>
 *           &lt;element name="valueSetPeriod" type="{http://hl7.org/fhir}Period"/>
 *           &lt;element name="valueSetRatio" type="{http://hl7.org/fhir}Ratio"/>
 *           &lt;element name="valueSetReference" type="{http://hl7.org/fhir}Reference"/>
 *           &lt;element name="valueSetSampledData" type="{http://hl7.org/fhir}SampledData"/>
 *           &lt;element name="valueSetSignature" type="{http://hl7.org/fhir}Signature"/>
 *           &lt;element name="valueSetHumanName" type="{http://hl7.org/fhir}HumanName"/>
 *           &lt;element name="valueSetAddress" type="{http://hl7.org/fhir}Address"/>
 *           &lt;element name="valueSetContactPoint" type="{http://hl7.org/fhir}ContactPoint"/>
 *           &lt;element name="valueSetTiming" type="{http://hl7.org/fhir}Timing"/>
 *           &lt;element name="valueSetMeta" type="{http://hl7.org/fhir}Meta"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementDefinition.Binding", propOrder = {
    "name",
    "strength",
    "description",
    "valueSetBoolean",
    "valueSetInteger",
    "valueSetDecimal",
    "valueSetBase64Binary",
    "valueSetInstant",
    "valueSetString",
    "valueSetUri",
    "valueSetDate",
    "valueSetDateTime",
    "valueSetTime",
    "valueSetCode",
    "valueSetOid",
    "valueSetUuid",
    "valueSetId",
    "valueSetUnsignedInt",
    "valueSetPositiveInt",
    "valueSetAttachment",
    "valueSetIdentifier",
    "valueSetCodeableConcept",
    "valueSetCoding",
    "valueSetQuantity",
    "valueSetRange",
    "valueSetPeriod",
    "valueSetRatio",
    "valueSetReference",
    "valueSetSampledData",
    "valueSetSignature",
    "valueSetHumanName",
    "valueSetAddress",
    "valueSetContactPoint",
    "valueSetTiming",
    "valueSetMeta"
})
public class ElementDefinitionBinding
    extends Element
{

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected BindingStrength strength;
    protected String description;
    protected Boolean valueSetBoolean;
    protected Integer valueSetInteger;
    protected Decimal valueSetDecimal;
    protected Base64Binary valueSetBase64Binary;
    protected Instant valueSetInstant;
    protected String valueSetString;
    protected Uri valueSetUri;
    protected Date valueSetDate;
    protected DateTime valueSetDateTime;
    protected Time valueSetTime;
    protected Code valueSetCode;
    protected Oid valueSetOid;
    protected Uuid valueSetUuid;
    protected Id valueSetId;
    protected UnsignedInt valueSetUnsignedInt;
    protected PositiveInt valueSetPositiveInt;
    protected Attachment valueSetAttachment;
    protected Identifier valueSetIdentifier;
    protected CodeableConcept valueSetCodeableConcept;
    protected Coding valueSetCoding;
    protected Quantity valueSetQuantity;
    protected Range valueSetRange;
    protected Period valueSetPeriod;
    protected Ratio valueSetRatio;
    protected Reference valueSetReference;
    protected SampledData valueSetSampledData;
    protected Signature valueSetSignature;
    protected HumanName valueSetHumanName;
    protected Address valueSetAddress;
    protected ContactPoint valueSetContactPoint;
    protected Timing valueSetTiming;
    protected Meta valueSetMeta;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return
     *     possible object is
     *     {@link BindingStrength }
     *     
     */
    public BindingStrength getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BindingStrength }
     *     
     */
    public void setStrength(BindingStrength value) {
        this.strength = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the valueSetBoolean property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getValueSetBoolean() {
        return valueSetBoolean;
    }

    /**
     * Sets the value of the valueSetBoolean property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValueSetBoolean(Boolean value) {
        this.valueSetBoolean = value;
    }

    /**
     * Gets the value of the valueSetInteger property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getValueSetInteger() {
        return valueSetInteger;
    }

    /**
     * Sets the value of the valueSetInteger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setValueSetInteger(Integer value) {
        this.valueSetInteger = value;
    }

    /**
     * Gets the value of the valueSetDecimal property.
     * 
     * @return
     *     possible object is
     *     {@link Decimal }
     *     
     */
    public Decimal getValueSetDecimal() {
        return valueSetDecimal;
    }

    /**
     * Sets the value of the valueSetDecimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Decimal }
     *     
     */
    public void setValueSetDecimal(Decimal value) {
        this.valueSetDecimal = value;
    }

    /**
     * Gets the value of the valueSetBase64Binary property.
     * 
     * @return
     *     possible object is
     *     {@link Base64Binary }
     *     
     */
    public Base64Binary getValueSetBase64Binary() {
        return valueSetBase64Binary;
    }

    /**
     * Sets the value of the valueSetBase64Binary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Base64Binary }
     *     
     */
    public void setValueSetBase64Binary(Base64Binary value) {
        this.valueSetBase64Binary = value;
    }

    /**
     * Gets the value of the valueSetInstant property.
     * 
     * @return
     *     possible object is
     *     {@link Instant }
     *     
     */
    public Instant getValueSetInstant() {
        return valueSetInstant;
    }

    /**
     * Sets the value of the valueSetInstant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Instant }
     *     
     */
    public void setValueSetInstant(Instant value) {
        this.valueSetInstant = value;
    }

    /**
     * Gets the value of the valueSetString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueSetString() {
        return valueSetString;
    }

    /**
     * Sets the value of the valueSetString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueSetString(String value) {
        this.valueSetString = value;
    }

    /**
     * Gets the value of the valueSetUri property.
     * 
     * @return
     *     possible object is
     *     {@link Uri }
     *     
     */
    public Uri getValueSetUri() {
        return valueSetUri;
    }

    /**
     * Sets the value of the valueSetUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uri }
     *     
     */
    public void setValueSetUri(Uri value) {
        this.valueSetUri = value;
    }

    /**
     * Gets the value of the valueSetDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getValueSetDate() {
        return valueSetDate;
    }

    /**
     * Sets the value of the valueSetDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setValueSetDate(Date value) {
        this.valueSetDate = value;
    }

    /**
     * Gets the value of the valueSetDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getValueSetDateTime() {
        return valueSetDateTime;
    }

    /**
     * Sets the value of the valueSetDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setValueSetDateTime(DateTime value) {
        this.valueSetDateTime = value;
    }

    /**
     * Gets the value of the valueSetTime property.
     * 
     * @return
     *     possible object is
     *     {@link Time }
     *     
     */
    public Time getValueSetTime() {
        return valueSetTime;
    }

    /**
     * Sets the value of the valueSetTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Time }
     *     
     */
    public void setValueSetTime(Time value) {
        this.valueSetTime = value;
    }

    /**
     * Gets the value of the valueSetCode property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getValueSetCode() {
        return valueSetCode;
    }

    /**
     * Sets the value of the valueSetCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setValueSetCode(Code value) {
        this.valueSetCode = value;
    }

    /**
     * Gets the value of the valueSetOid property.
     * 
     * @return
     *     possible object is
     *     {@link Oid }
     *     
     */
    public Oid getValueSetOid() {
        return valueSetOid;
    }

    /**
     * Sets the value of the valueSetOid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Oid }
     *     
     */
    public void setValueSetOid(Oid value) {
        this.valueSetOid = value;
    }

    /**
     * Gets the value of the valueSetUuid property.
     * 
     * @return
     *     possible object is
     *     {@link Uuid }
     *     
     */
    public Uuid getValueSetUuid() {
        return valueSetUuid;
    }

    /**
     * Sets the value of the valueSetUuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uuid }
     *     
     */
    public void setValueSetUuid(Uuid value) {
        this.valueSetUuid = value;
    }

    /**
     * Gets the value of the valueSetId property.
     * 
     * @return
     *     possible object is
     *     {@link Id }
     *     
     */
    public Id getValueSetId() {
        return valueSetId;
    }

    /**
     * Sets the value of the valueSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Id }
     *     
     */
    public void setValueSetId(Id value) {
        this.valueSetId = value;
    }

    /**
     * Gets the value of the valueSetUnsignedInt property.
     * 
     * @return
     *     possible object is
     *     {@link UnsignedInt }
     *     
     */
    public UnsignedInt getValueSetUnsignedInt() {
        return valueSetUnsignedInt;
    }

    /**
     * Sets the value of the valueSetUnsignedInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedInt }
     *     
     */
    public void setValueSetUnsignedInt(UnsignedInt value) {
        this.valueSetUnsignedInt = value;
    }

    /**
     * Gets the value of the valueSetPositiveInt property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveInt }
     *     
     */
    public PositiveInt getValueSetPositiveInt() {
        return valueSetPositiveInt;
    }

    /**
     * Sets the value of the valueSetPositiveInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveInt }
     *     
     */
    public void setValueSetPositiveInt(PositiveInt value) {
        this.valueSetPositiveInt = value;
    }

    /**
     * Gets the value of the valueSetAttachment property.
     * 
     * @return
     *     possible object is
     *     {@link Attachment }
     *     
     */
    public Attachment getValueSetAttachment() {
        return valueSetAttachment;
    }

    /**
     * Sets the value of the valueSetAttachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Attachment }
     *     
     */
    public void setValueSetAttachment(Attachment value) {
        this.valueSetAttachment = value;
    }

    /**
     * Gets the value of the valueSetIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getValueSetIdentifier() {
        return valueSetIdentifier;
    }

    /**
     * Sets the value of the valueSetIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setValueSetIdentifier(Identifier value) {
        this.valueSetIdentifier = value;
    }

    /**
     * Gets the value of the valueSetCodeableConcept property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getValueSetCodeableConcept() {
        return valueSetCodeableConcept;
    }

    /**
     * Sets the value of the valueSetCodeableConcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setValueSetCodeableConcept(CodeableConcept value) {
        this.valueSetCodeableConcept = value;
    }

    /**
     * Gets the value of the valueSetCoding property.
     * 
     * @return
     *     possible object is
     *     {@link Coding }
     *     
     */
    public Coding getValueSetCoding() {
        return valueSetCoding;
    }

    /**
     * Sets the value of the valueSetCoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coding }
     *     
     */
    public void setValueSetCoding(Coding value) {
        this.valueSetCoding = value;
    }

    /**
     * Gets the value of the valueSetQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getValueSetQuantity() {
        return valueSetQuantity;
    }

    /**
     * Sets the value of the valueSetQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setValueSetQuantity(Quantity value) {
        this.valueSetQuantity = value;
    }

    /**
     * Gets the value of the valueSetRange property.
     * 
     * @return
     *     possible object is
     *     {@link Range }
     *     
     */
    public Range getValueSetRange() {
        return valueSetRange;
    }

    /**
     * Sets the value of the valueSetRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Range }
     *     
     */
    public void setValueSetRange(Range value) {
        this.valueSetRange = value;
    }

    /**
     * Gets the value of the valueSetPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getValueSetPeriod() {
        return valueSetPeriod;
    }

    /**
     * Sets the value of the valueSetPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setValueSetPeriod(Period value) {
        this.valueSetPeriod = value;
    }

    /**
     * Gets the value of the valueSetRatio property.
     * 
     * @return
     *     possible object is
     *     {@link Ratio }
     *     
     */
    public Ratio getValueSetRatio() {
        return valueSetRatio;
    }

    /**
     * Sets the value of the valueSetRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ratio }
     *     
     */
    public void setValueSetRatio(Ratio value) {
        this.valueSetRatio = value;
    }

    /**
     * Gets the value of the valueSetReference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getValueSetReference() {
        return valueSetReference;
    }

    /**
     * Sets the value of the valueSetReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setValueSetReference(Reference value) {
        this.valueSetReference = value;
    }

    /**
     * Gets the value of the valueSetSampledData property.
     * 
     * @return
     *     possible object is
     *     {@link SampledData }
     *     
     */
    public SampledData getValueSetSampledData() {
        return valueSetSampledData;
    }

    /**
     * Sets the value of the valueSetSampledData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SampledData }
     *     
     */
    public void setValueSetSampledData(SampledData value) {
        this.valueSetSampledData = value;
    }

    /**
     * Gets the value of the valueSetSignature property.
     * 
     * @return
     *     possible object is
     *     {@link Signature }
     *     
     */
    public Signature getValueSetSignature() {
        return valueSetSignature;
    }

    /**
     * Sets the value of the valueSetSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Signature }
     *     
     */
    public void setValueSetSignature(Signature value) {
        this.valueSetSignature = value;
    }

    /**
     * Gets the value of the valueSetHumanName property.
     * 
     * @return
     *     possible object is
     *     {@link HumanName }
     *     
     */
    public HumanName getValueSetHumanName() {
        return valueSetHumanName;
    }

    /**
     * Sets the value of the valueSetHumanName property.
     * 
     * @param value
     *     allowed object is
     *     {@link HumanName }
     *     
     */
    public void setValueSetHumanName(HumanName value) {
        this.valueSetHumanName = value;
    }

    /**
     * Gets the value of the valueSetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getValueSetAddress() {
        return valueSetAddress;
    }

    /**
     * Sets the value of the valueSetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setValueSetAddress(Address value) {
        this.valueSetAddress = value;
    }

    /**
     * Gets the value of the valueSetContactPoint property.
     * 
     * @return
     *     possible object is
     *     {@link ContactPoint }
     *     
     */
    public ContactPoint getValueSetContactPoint() {
        return valueSetContactPoint;
    }

    /**
     * Sets the value of the valueSetContactPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactPoint }
     *     
     */
    public void setValueSetContactPoint(ContactPoint value) {
        this.valueSetContactPoint = value;
    }

    /**
     * Gets the value of the valueSetTiming property.
     * 
     * @return
     *     possible object is
     *     {@link Timing }
     *     
     */
    public Timing getValueSetTiming() {
        return valueSetTiming;
    }

    /**
     * Sets the value of the valueSetTiming property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timing }
     *     
     */
    public void setValueSetTiming(Timing value) {
        this.valueSetTiming = value;
    }

    /**
     * Gets the value of the valueSetMeta property.
     * 
     * @return
     *     possible object is
     *     {@link Meta }
     *     
     */
    public Meta getValueSetMeta() {
        return valueSetMeta;
    }

    /**
     * Sets the value of the valueSetMeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta }
     *     
     */
    public void setValueSetMeta(Meta value) {
        this.valueSetMeta = value;
    }

}
