//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.07 at 01:41:53 PM EDT 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventTiming-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventTiming-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HS"/>
 *     &lt;enumeration value="WAKE"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="CM"/>
 *     &lt;enumeration value="CD"/>
 *     &lt;enumeration value="CV"/>
 *     &lt;enumeration value="AC"/>
 *     &lt;enumeration value="ACM"/>
 *     &lt;enumeration value="ACD"/>
 *     &lt;enumeration value="ACV"/>
 *     &lt;enumeration value="PC"/>
 *     &lt;enumeration value="PCM"/>
 *     &lt;enumeration value="PCD"/>
 *     &lt;enumeration value="PCV"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EventTiming-list")
@XmlEnum
public enum EventTimingList {


    /**
     * event occurs [duration] before the hour of sleep
     * 						(or trying to).
     * 					
     * 
     */
    HS,

    /**
     * event occurs [duration] after waking.
     * 					
     * 
     */
    WAKE,

    /**
     * event occurs at a meal (from the Latin cibus).
     * 					
     * 
     */
    C,

    /**
     * event occurs at breakfast (from the Latin cibus
     * 						matutinus).
     * 					
     * 
     */
    CM,

    /**
     * event occurs at lunch (from the Latin cibus
     * 						diurnus).
     * 					
     * 
     */
    CD,

    /**
     * event occurs at dinner (from the Latin ante cibus
     * 						vespertinus).
     * 					
     * 
     */
    CV,

    /**
     * event occurs [duration] before a meal (from the
     * 						Latin ante cibus).
     * 					
     * 
     */
    AC,

    /**
     * event occurs [duration] before breakfast (from
     * 						the Latin ante cibus matutinus).
     * 					
     * 
     */
    ACM,

    /**
     * event occurs [duration] before lunch (from the
     * 						Latin ante cibus diurnus).
     * 					
     * 
     */
    ACD,

    /**
     * event occurs [duration] before dinner (from the
     * 						Latin ante cibus vespertinus).
     * 					
     * 
     */
    ACV,

    /**
     * event occurs [duration] after a meal (from the
     * 						Latin post cibus).
     * 					
     * 
     */
    PC,

    /**
     * event occurs [duration] after breakfast (from the
     * 						Latin post cibus matutinus).
     * 					
     * 
     */
    PCM,

    /**
     * event occurs [duration] after lunch (from the
     * 						Latin post cibus diurnus).
     * 					
     * 
     */
    PCD,

    /**
     * event occurs [duration] after dinner (from the
     * 						Latin post cibus vespertinus).
     * 					
     * 
     */
    PCV;

    public java.lang.String value() {
        return name();
    }

    public static EventTimingList fromValue(java.lang.String v) {
        return valueOf(v);
    }

}
