//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.07 at 01:41:53 PM EDT 
//


package org.hl7.fhir;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hl7.fhir package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Parameters_QNAME = new QName("http://hl7.org/fhir", "Parameters");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hl7.fhir
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link DomainResource }
     * 
     */
    public DomainResource createDomainResource() {
        return new DomainResource();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link NameUse }
     * 
     */
    public NameUse createNameUse() {
        return new NameUse();
    }

    /**
     * Create an instance of {@link AggregationMode }
     * 
     */
    public AggregationMode createAggregationMode() {
        return new AggregationMode();
    }

    /**
     * Create an instance of {@link Count }
     * 
     */
    public Count createCount() {
        return new Count();
    }

    /**
     * Create an instance of {@link ElementDefinitionSlicing }
     * 
     */
    public ElementDefinitionSlicing createElementDefinitionSlicing() {
        return new ElementDefinitionSlicing();
    }

    /**
     * Create an instance of {@link EncounterClass }
     * 
     */
    public EncounterClass createEncounterClass() {
        return new EncounterClass();
    }

    /**
     * Create an instance of {@link Coding }
     * 
     */
    public Coding createCoding() {
        return new Coding();
    }

    /**
     * Create an instance of {@link SampledData }
     * 
     */
    public SampledData createSampledData() {
        return new SampledData();
    }

    /**
     * Create an instance of {@link Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link PositiveInt }
     * 
     */
    public PositiveInt createPositiveInt() {
        return new PositiveInt();
    }

    /**
     * Create an instance of {@link ElementDefinition }
     * 
     */
    public ElementDefinition createElementDefinition() {
        return new ElementDefinition();
    }

    /**
     * Create an instance of {@link Distance }
     * 
     */
    public Distance createDistance() {
        return new Distance();
    }

    /**
     * Create an instance of {@link EncounterState }
     * 
     */
    public EncounterState createEncounterState() {
        return new EncounterState();
    }

    /**
     * Create an instance of {@link Timing }
     * 
     */
    public Timing createTiming() {
        return new Timing();
    }

    /**
     * Create an instance of {@link ElementDefinitionBinding }
     * 
     */
    public ElementDefinitionBinding createElementDefinitionBinding() {
        return new ElementDefinitionBinding();
    }

    /**
     * Create an instance of {@link DateTime }
     * 
     */
    public DateTime createDateTime() {
        return new DateTime();
    }

    /**
     * Create an instance of {@link QuantityComparator }
     * 
     */
    public QuantityComparator createQuantityComparator() {
        return new QuantityComparator();
    }

    /**
     * Create an instance of {@link MessageEvent }
     * 
     */
    public MessageEvent createMessageEvent() {
        return new MessageEvent();
    }

    /**
     * Create an instance of {@link Instant }
     * 
     */
    public Instant createInstant() {
        return new Instant();
    }

    /**
     * Create an instance of {@link ContactPoint }
     * 
     */
    public ContactPoint createContactPoint() {
        return new ContactPoint();
    }

    /**
     * Create an instance of {@link ElementDefinitionMapping }
     * 
     */
    public ElementDefinitionMapping createElementDefinitionMapping() {
        return new ElementDefinitionMapping();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link Ratio }
     * 
     */
    public Ratio createRatio() {
        return new Ratio();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link IdentifierUse }
     * 
     */
    public IdentifierUse createIdentifierUse() {
        return new IdentifierUse();
    }

    /**
     * Create an instance of {@link Uri }
     * 
     */
    public Uri createUri() {
        return new Uri();
    }

    /**
     * Create an instance of {@link AdministrativeGender }
     * 
     */
    public AdministrativeGender createAdministrativeGender() {
        return new AdministrativeGender();
    }

    /**
     * Create an instance of {@link BackboneElement }
     * 
     */
    public BackboneElement createBackboneElement() {
        return new BackboneElement();
    }

    /**
     * Create an instance of {@link QuestionnaireStatus }
     * 
     */
    public QuestionnaireStatus createQuestionnaireStatus() {
        return new QuestionnaireStatus();
    }

    /**
     * Create an instance of {@link NoteType }
     * 
     */
    public NoteType createNoteType() {
        return new NoteType();
    }

    /**
     * Create an instance of {@link BindingStrength }
     * 
     */
    public BindingStrength createBindingStrength() {
        return new BindingStrength();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link EventTiming }
     * 
     */
    public EventTiming createEventTiming() {
        return new EventTiming();
    }

    /**
     * Create an instance of {@link ElementDefinitionConstraint }
     * 
     */
    public ElementDefinitionConstraint createElementDefinitionConstraint() {
        return new ElementDefinitionConstraint();
    }

    /**
     * Create an instance of {@link ConformanceResourceStatus }
     * 
     */
    public ConformanceResourceStatus createConformanceResourceStatus() {
        return new ConformanceResourceStatus();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link Integer }
     * 
     */
    public Integer createInteger() {
        return new Integer();
    }

    /**
     * Create an instance of {@link ConstraintSeverity }
     * 
     */
    public ConstraintSeverity createConstraintSeverity() {
        return new ConstraintSeverity();
    }

    /**
     * Create an instance of {@link Uuid }
     * 
     */
    public Uuid createUuid() {
        return new Uuid();
    }

    /**
     * Create an instance of {@link ParametersPart }
     * 
     */
    public ParametersPart createParametersPart() {
        return new ParametersPart();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link FHIRDefinedType }
     * 
     */
    public FHIRDefinedType createFHIRDefinedType() {
        return new FHIRDefinedType();
    }

    /**
     * Create an instance of {@link Narrative }
     * 
     */
    public Narrative createNarrative() {
        return new Narrative();
    }

    /**
     * Create an instance of {@link ClinicalBaseGender }
     * 
     */
    public ClinicalBaseGender createClinicalBaseGender() {
        return new ClinicalBaseGender();
    }

    /**
     * Create an instance of {@link ContactPointSystem }
     * 
     */
    public ContactPointSystem createContactPointSystem() {
        return new ContactPointSystem();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link Duration }
     * 
     */
    public Duration createDuration() {
        return new Duration();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link DataAbsentReason }
     * 
     */
    public DataAbsentReason createDataAbsentReason() {
        return new DataAbsentReason();
    }

    /**
     * Create an instance of {@link MaritalStatus }
     * 
     */
    public MaritalStatus createMaritalStatus() {
        return new MaritalStatus();
    }

    /**
     * Create an instance of {@link CompositionStatus }
     * 
     */
    public CompositionStatus createCompositionStatus() {
        return new CompositionStatus();
    }

    /**
     * Create an instance of {@link RemittanceOutcome }
     * 
     */
    public RemittanceOutcome createRemittanceOutcome() {
        return new RemittanceOutcome();
    }

    /**
     * Create an instance of {@link Base64Binary }
     * 
     */
    public Base64Binary createBase64Binary() {
        return new Base64Binary();
    }

    /**
     * Create an instance of {@link SpecialValues }
     * 
     */
    public SpecialValues createSpecialValues() {
        return new SpecialValues();
    }

    /**
     * Create an instance of {@link SampledDataDataType }
     * 
     */
    public SampledDataDataType createSampledDataDataType() {
        return new SampledDataDataType();
    }

    /**
     * Create an instance of {@link Decimal }
     * 
     */
    public Decimal createDecimal() {
        return new Decimal();
    }

    /**
     * Create an instance of {@link DocumentReferenceStatus }
     * 
     */
    public DocumentReferenceStatus createDocumentReferenceStatus() {
        return new DocumentReferenceStatus();
    }

    /**
     * Create an instance of {@link CodeableConcept }
     * 
     */
    public CodeableConcept createCodeableConcept() {
        return new CodeableConcept();
    }

    /**
     * Create an instance of {@link ConformanceUseContext }
     * 
     */
    public ConformanceUseContext createConformanceUseContext() {
        return new ConformanceUseContext();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link String }
     * 
     */
    public String createString() {
        return new String();
    }

    /**
     * Create an instance of {@link PropertyRepresentation }
     * 
     */
    public PropertyRepresentation createPropertyRepresentation() {
        return new PropertyRepresentation();
    }

    /**
     * Create an instance of {@link Element }
     * 
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link Oid }
     * 
     */
    public Oid createOid() {
        return new Oid();
    }

    /**
     * Create an instance of {@link NarrativeStatus }
     * 
     */
    public NarrativeStatus createNarrativeStatus() {
        return new NarrativeStatus();
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link HumanName }
     * 
     */
    public HumanName createHumanName() {
        return new HumanName();
    }

    /**
     * Create an instance of {@link AddressUse }
     * 
     */
    public AddressUse createAddressUse() {
        return new AddressUse();
    }

    /**
     * Create an instance of {@link TimingRepeat }
     * 
     */
    public TimingRepeat createTimingRepeat() {
        return new TimingRepeat();
    }

    /**
     * Create an instance of {@link Age }
     * 
     */
    public Age createAge() {
        return new Age();
    }

    /**
     * Create an instance of {@link ContactPointUse }
     * 
     */
    public ContactPointUse createContactPointUse() {
        return new ContactPointUse();
    }

    /**
     * Create an instance of {@link ElementDefinitionType }
     * 
     */
    public ElementDefinitionType createElementDefinitionType() {
        return new ElementDefinitionType();
    }

    /**
     * Create an instance of {@link Quantity }
     * 
     */
    public Quantity createQuantity() {
        return new Quantity();
    }

    /**
     * Create an instance of {@link SearchParamType }
     * 
     */
    public SearchParamType createSearchParamType() {
        return new SearchParamType();
    }

    /**
     * Create an instance of {@link UnitsOfTime }
     * 
     */
    public UnitsOfTime createUnitsOfTime() {
        return new UnitsOfTime();
    }

    /**
     * Create an instance of {@link ParametersParameter }
     * 
     */
    public ParametersParameter createParametersParameter() {
        return new ParametersParameter();
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

    /**
     * Create an instance of {@link Boolean }
     * 
     */
    public Boolean createBoolean() {
        return new Boolean();
    }

    /**
     * Create an instance of {@link Signature }
     * 
     */
    public Signature createSignature() {
        return new Signature();
    }

    /**
     * Create an instance of {@link UnsignedInt }
     * 
     */
    public UnsignedInt createUnsignedInt() {
        return new UnsignedInt();
    }

    /**
     * Create an instance of {@link SlicingRules }
     * 
     */
    public SlicingRules createSlicingRules() {
        return new SlicingRules();
    }

    /**
     * Create an instance of {@link CompositionAttestationMode }
     * 
     */
    public CompositionAttestationMode createCompositionAttestationMode() {
        return new CompositionAttestationMode();
    }

    /**
     * Create an instance of {@link Time }
     * 
     */
    public Time createTime() {
        return new Time();
    }

    /**
     * Create an instance of {@link ResourceContainer }
     * 
     */
    public ResourceContainer createResourceContainer() {
        return new ResourceContainer();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Parameters }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hl7.org/fhir", name = "Parameters")
    public JAXBElement<Parameters> createParameters(Parameters value) {
        return new JAXBElement<Parameters>(_Parameters_QNAME, Parameters.class, null, value);
    }

}
