//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.20 at 11:19:26 AM EST 
//


package org.hl7.fhir;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hl7.fhir package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Device_QNAME = new QName("http://hl7.org/fhir", "Device");
    private final static QName _Observation_QNAME = new QName("http://hl7.org/fhir", "Observation");
    private final static QName _Location_QNAME = new QName("http://hl7.org/fhir", "Location");
    private final static QName _DiagnosticOrder_QNAME = new QName("http://hl7.org/fhir", "DiagnosticOrder");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hl7.fhir
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Observation }
     * 
     */
    public Observation createObservation() {
        return new Observation();
    }

    /**
     * Create an instance of {@link DiagnosticOrder }
     * 
     */
    public DiagnosticOrder createDiagnosticOrder() {
        return new DiagnosticOrder();
    }

    /**
     * Create an instance of {@link SampledDataDataType }
     * 
     */
    public SampledDataDataType createSampledDataDataType() {
        return new SampledDataDataType();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link Base64Binary }
     * 
     */
    public Base64Binary createBase64Binary() {
        return new Base64Binary();
    }

    /**
     * Create an instance of {@link AddressUse }
     * 
     */
    public AddressUse createAddressUse() {
        return new AddressUse();
    }

    /**
     * Create an instance of {@link HumanName }
     * 
     */
    public HumanName createHumanName() {
        return new HumanName();
    }

    /**
     * Create an instance of {@link ScheduleRepeat }
     * 
     */
    public ScheduleRepeat createScheduleRepeat() {
        return new ScheduleRepeat();
    }

    /**
     * Create an instance of {@link Boolean }
     * 
     */
    public Boolean createBoolean() {
        return new Boolean();
    }

    /**
     * Create an instance of {@link CodeableConcept }
     * 
     */
    public CodeableConcept createCodeableConcept() {
        return new CodeableConcept();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link Instant }
     * 
     */
    public Instant createInstant() {
        return new Instant();
    }

    /**
     * Create an instance of {@link Coding }
     * 
     */
    public Coding createCoding() {
        return new Coding();
    }

    /**
     * Create an instance of {@link IdentifierUse }
     * 
     */
    public IdentifierUse createIdentifierUse() {
        return new IdentifierUse();
    }

    /**
     * Create an instance of {@link LocationPosition }
     * 
     */
    public LocationPosition createLocationPosition() {
        return new LocationPosition();
    }

    /**
     * Create an instance of {@link Uuid }
     * 
     */
    public Uuid createUuid() {
        return new Uuid();
    }

    /**
     * Create an instance of {@link ObservationRelationshipType }
     * 
     */
    public ObservationRelationshipType createObservationRelationshipType() {
        return new ObservationRelationshipType();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link UnitsOfTime }
     * 
     */
    public UnitsOfTime createUnitsOfTime() {
        return new UnitsOfTime();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link DocumentReferenceStatus }
     * 
     */
    public DocumentReferenceStatus createDocumentReferenceStatus() {
        return new DocumentReferenceStatus();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link Oid }
     * 
     */
    public Oid createOid() {
        return new Oid();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link Integer }
     * 
     */
    public Integer createInteger() {
        return new Integer();
    }

    /**
     * Create an instance of {@link QuantityCompararator }
     * 
     */
    public QuantityCompararator createQuantityCompararator() {
        return new QuantityCompararator();
    }

    /**
     * Create an instance of {@link ObservationReferenceRange }
     * 
     */
    public ObservationReferenceRange createObservationReferenceRange() {
        return new ObservationReferenceRange();
    }

    /**
     * Create an instance of {@link String }
     * 
     */
    public String createString() {
        return new String();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link SampledData }
     * 
     */
    public SampledData createSampledData() {
        return new SampledData();
    }

    /**
     * Create an instance of {@link ResourceReference }
     * 
     */
    public ResourceReference createResourceReference() {
        return new ResourceReference();
    }

    /**
     * Create an instance of {@link Element }
     * 
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link Narrative }
     * 
     */
    public Narrative createNarrative() {
        return new Narrative();
    }

    /**
     * Create an instance of {@link NarrativeStatus }
     * 
     */
    public NarrativeStatus createNarrativeStatus() {
        return new NarrativeStatus();
    }

    /**
     * Create an instance of {@link DiagnosticOrderEvent }
     * 
     */
    public DiagnosticOrderEvent createDiagnosticOrderEvent() {
        return new DiagnosticOrderEvent();
    }

    /**
     * Create an instance of {@link DiagnosticOrderPriority }
     * 
     */
    public DiagnosticOrderPriority createDiagnosticOrderPriority() {
        return new DiagnosticOrderPriority();
    }

    /**
     * Create an instance of {@link ObservationStatus }
     * 
     */
    public ObservationStatus createObservationStatus() {
        return new ObservationStatus();
    }

    /**
     * Create an instance of {@link LocationStatus }
     * 
     */
    public LocationStatus createLocationStatus() {
        return new LocationStatus();
    }

    /**
     * Create an instance of {@link Extension }
     * 
     */
    public Extension createExtension() {
        return new Extension();
    }

    /**
     * Create an instance of {@link LocationMode }
     * 
     */
    public LocationMode createLocationMode() {
        return new LocationMode();
    }

    /**
     * Create an instance of {@link ContactUse }
     * 
     */
    public ContactUse createContactUse() {
        return new ContactUse();
    }

    /**
     * Create an instance of {@link Distance }
     * 
     */
    public Distance createDistance() {
        return new Distance();
    }

    /**
     * Create an instance of {@link BackboneElement }
     * 
     */
    public BackboneElement createBackboneElement() {
        return new BackboneElement();
    }

    /**
     * Create an instance of {@link ContactSystem }
     * 
     */
    public ContactSystem createContactSystem() {
        return new ContactSystem();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link ObservationReliability }
     * 
     */
    public ObservationReliability createObservationReliability() {
        return new ObservationReliability();
    }

    /**
     * Create an instance of {@link Uri }
     * 
     */
    public Uri createUri() {
        return new Uri();
    }

    /**
     * Create an instance of {@link SearchParamType }
     * 
     */
    public SearchParamType createSearchParamType() {
        return new SearchParamType();
    }

    /**
     * Create an instance of {@link Age }
     * 
     */
    public Age createAge() {
        return new Age();
    }

    /**
     * Create an instance of {@link Count }
     * 
     */
    public Count createCount() {
        return new Count();
    }

    /**
     * Create an instance of {@link DateTime }
     * 
     */
    public DateTime createDateTime() {
        return new DateTime();
    }

    /**
     * Create an instance of {@link Id }
     * 
     */
    public Id createId() {
        return new Id();
    }

    /**
     * Create an instance of {@link EventTiming }
     * 
     */
    public EventTiming createEventTiming() {
        return new EventTiming();
    }

    /**
     * Create an instance of {@link Ratio }
     * 
     */
    public Ratio createRatio() {
        return new Ratio();
    }

    /**
     * Create an instance of {@link Duration }
     * 
     */
    public Duration createDuration() {
        return new Duration();
    }

    /**
     * Create an instance of {@link NameUse }
     * 
     */
    public NameUse createNameUse() {
        return new NameUse();
    }

    /**
     * Create an instance of {@link ObservationRelated }
     * 
     */
    public ObservationRelated createObservationRelated() {
        return new ObservationRelated();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link ResourceInline }
     * 
     */
    public ResourceInline createResourceInline() {
        return new ResourceInline();
    }

    /**
     * Create an instance of {@link Quantity }
     * 
     */
    public Quantity createQuantity() {
        return new Quantity();
    }

    /**
     * Create an instance of {@link ValueSetStatus }
     * 
     */
    public ValueSetStatus createValueSetStatus() {
        return new ValueSetStatus();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link Decimal }
     * 
     */
    public Decimal createDecimal() {
        return new Decimal();
    }

    /**
     * Create an instance of {@link DiagnosticOrderItem }
     * 
     */
    public DiagnosticOrderItem createDiagnosticOrderItem() {
        return new DiagnosticOrderItem();
    }

    /**
     * Create an instance of {@link DiagnosticOrderStatus }
     * 
     */
    public DiagnosticOrderStatus createDiagnosticOrderStatus() {
        return new DiagnosticOrderStatus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Device }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hl7.org/fhir", name = "Device")
    public JAXBElement<Device> createDevice(Device value) {
        return new JAXBElement<Device>(_Device_QNAME, Device.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Observation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hl7.org/fhir", name = "Observation")
    public JAXBElement<Observation> createObservation(Observation value) {
        return new JAXBElement<Observation>(_Observation_QNAME, Observation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Location }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hl7.org/fhir", name = "Location")
    public JAXBElement<Location> createLocation(Location value) {
        return new JAXBElement<Location>(_Location_QNAME, Location.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DiagnosticOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hl7.org/fhir", name = "DiagnosticOrder")
    public JAXBElement<DiagnosticOrder> createDiagnosticOrder(DiagnosticOrder value) {
        return new JAXBElement<DiagnosticOrder>(_DiagnosticOrder_QNAME, DiagnosticOrder.class, null, value);
    }

}
