//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.07 at 01:41:53 PM EDT 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyRepresentation-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PropertyRepresentation-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="xmlAttr"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PropertyRepresentation-list")
@XmlEnum
public enum PropertyRepresentationList {


    /**
     * In XML, this property is represented as an
     * 						attribute not an element.
     * 					
     * 
     */
    @XmlEnumValue("xmlAttr")
    XML_ATTR("xmlAttr");
    private final java.lang.String value;

    PropertyRepresentationList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static PropertyRepresentationList fromValue(java.lang.String v) {
        for (PropertyRepresentationList c: PropertyRepresentationList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
