//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.07 at 01:41:53 PM EDT 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceType-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResourceType-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AllergyIntolerance"/>
 *     &lt;enumeration value="Appointment"/>
 *     &lt;enumeration value="AppointmentResponse"/>
 *     &lt;enumeration value="AuditEvent"/>
 *     &lt;enumeration value="Basic"/>
 *     &lt;enumeration value="Binary"/>
 *     &lt;enumeration value="BodySite"/>
 *     &lt;enumeration value="Bundle"/>
 *     &lt;enumeration value="CarePlan"/>
 *     &lt;enumeration value="Claim"/>
 *     &lt;enumeration value="ClaimResponse"/>
 *     &lt;enumeration value="ClinicalImpression"/>
 *     &lt;enumeration value="Communication"/>
 *     &lt;enumeration value="CommunicationRequest"/>
 *     &lt;enumeration value="Composition"/>
 *     &lt;enumeration value="ConceptMap"/>
 *     &lt;enumeration value="Condition"/>
 *     &lt;enumeration value="Conformance"/>
 *     &lt;enumeration value="Contract"/>
 *     &lt;enumeration value="Contraindication"/>
 *     &lt;enumeration value="Coverage"/>
 *     &lt;enumeration value="DataElement"/>
 *     &lt;enumeration value="Device"/>
 *     &lt;enumeration value="DeviceComponent"/>
 *     &lt;enumeration value="DeviceMetric"/>
 *     &lt;enumeration value="DeviceUseRequest"/>
 *     &lt;enumeration value="DeviceUseStatement"/>
 *     &lt;enumeration value="DiagnosticOrder"/>
 *     &lt;enumeration value="DiagnosticReport"/>
 *     &lt;enumeration value="DocumentManifest"/>
 *     &lt;enumeration value="DocumentReference"/>
 *     &lt;enumeration value="EligibilityRequest"/>
 *     &lt;enumeration value="EligibilityResponse"/>
 *     &lt;enumeration value="Encounter"/>
 *     &lt;enumeration value="EnrollmentRequest"/>
 *     &lt;enumeration value="EnrollmentResponse"/>
 *     &lt;enumeration value="EpisodeOfCare"/>
 *     &lt;enumeration value="ExplanationOfBenefit"/>
 *     &lt;enumeration value="FamilyMemberHistory"/>
 *     &lt;enumeration value="Flag"/>
 *     &lt;enumeration value="Goal"/>
 *     &lt;enumeration value="Group"/>
 *     &lt;enumeration value="HealthcareService"/>
 *     &lt;enumeration value="ImagingObjectSelection"/>
 *     &lt;enumeration value="ImagingStudy"/>
 *     &lt;enumeration value="Immunization"/>
 *     &lt;enumeration value="ImmunizationRecommendation"/>
 *     &lt;enumeration value="List"/>
 *     &lt;enumeration value="Location"/>
 *     &lt;enumeration value="Media"/>
 *     &lt;enumeration value="Medication"/>
 *     &lt;enumeration value="MedicationAdministration"/>
 *     &lt;enumeration value="MedicationDispense"/>
 *     &lt;enumeration value="MedicationPrescription"/>
 *     &lt;enumeration value="MedicationStatement"/>
 *     &lt;enumeration value="MessageHeader"/>
 *     &lt;enumeration value="NamingSystem"/>
 *     &lt;enumeration value="NutritionOrder"/>
 *     &lt;enumeration value="Observation"/>
 *     &lt;enumeration value="OperationDefinition"/>
 *     &lt;enumeration value="OperationOutcome"/>
 *     &lt;enumeration value="Order"/>
 *     &lt;enumeration value="OrderResponse"/>
 *     &lt;enumeration value="Organization"/>
 *     &lt;enumeration value="Patient"/>
 *     &lt;enumeration value="PaymentNotice"/>
 *     &lt;enumeration value="PaymentReconciliation"/>
 *     &lt;enumeration value="Person"/>
 *     &lt;enumeration value="Practitioner"/>
 *     &lt;enumeration value="Procedure"/>
 *     &lt;enumeration value="ProcedureRequest"/>
 *     &lt;enumeration value="ProcessRequest"/>
 *     &lt;enumeration value="ProcessResponse"/>
 *     &lt;enumeration value="Provenance"/>
 *     &lt;enumeration value="Questionnaire"/>
 *     &lt;enumeration value="QuestionnaireAnswers"/>
 *     &lt;enumeration value="ReferralRequest"/>
 *     &lt;enumeration value="RelatedPerson"/>
 *     &lt;enumeration value="RiskAssessment"/>
 *     &lt;enumeration value="Schedule"/>
 *     &lt;enumeration value="SearchParameter"/>
 *     &lt;enumeration value="Slot"/>
 *     &lt;enumeration value="Specimen"/>
 *     &lt;enumeration value="StructureDefinition"/>
 *     &lt;enumeration value="Subscription"/>
 *     &lt;enumeration value="Substance"/>
 *     &lt;enumeration value="Supply"/>
 *     &lt;enumeration value="SupplyDelivery"/>
 *     &lt;enumeration value="SupplyRequest"/>
 *     &lt;enumeration value="ValueSet"/>
 *     &lt;enumeration value="VisionPrescription"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResourceType-list")
@XmlEnum
public enum ResourceTypeList {


    /**
     * Risk of harmful or undesirable, physiological
     * 						response which is unique to an individual and associated with
     * 						exposure to a substance.
     * 					
     * 
     */
    @XmlEnumValue("AllergyIntolerance")
    ALLERGY_INTOLERANCE("AllergyIntolerance"),

    /**
     * A booking of a healthcare event among patient(s),
     * 						practitioner(s), related person(s) and/or device(s) for a specific
     * 						date/time. This may result in one or more Encounter(s).
     * 					
     * 
     */
    @XmlEnumValue("Appointment")
    APPOINTMENT("Appointment"),

    /**
     * A reply to an appointment request for a patient
     * 						and/or practitioner(s), such as a confirmation or rejection.
     * 					
     * 
     */
    @XmlEnumValue("AppointmentResponse")
    APPOINTMENT_RESPONSE("AppointmentResponse"),

    /**
     * A record of an event made for purposes of
     * 						maintaining a security log. Typical uses include detection of
     * 						intrusion attempts and monitoring for inappropriate usage.
     * 					
     * 
     */
    @XmlEnumValue("AuditEvent")
    AUDIT_EVENT("AuditEvent"),

    /**
     * Basic is used for handling concepts not yet
     * 						defined in FHIR, narrative-only resources that don't map to an
     * 						existing resource, and custom resources not appropriate for
     * 						inclusion in the FHIR specification.
     * 					
     * 
     */
    @XmlEnumValue("Basic")
    BASIC("Basic"),

    /**
     * A binary resource can contain any content,
     * 						whether text, image, pdf, zip archive, etc.
     * 					
     * 
     */
    @XmlEnumValue("Binary")
    BINARY("Binary"),

    /**
     * Record details about the anatomical location of a
     * 						specimen or body part. This resource may be used when a coded
     * 						concept does not provide the necessary detail needed for the use
     * 						case.
     * 					
     * 
     */
    @XmlEnumValue("BodySite")
    BODY_SITE("BodySite"),

    /**
     * A container for a collection of resources.
     * 					
     * 
     */
    @XmlEnumValue("Bundle")
    BUNDLE("Bundle"),

    /**
     * Describes the intention of how one or more
     * 						practitioners intend to deliver care for a particular patient for
     * 						a period of time, possibly limited to care for a specific
     * 						condition or set of conditions.
     * 					
     * 
     */
    @XmlEnumValue("CarePlan")
    CARE_PLAN("CarePlan"),

    /**
     * A provider issued list of services and products
     * 						provided, or to be provided, to a patient which is provided to an
     * 						insurer for payment recovery.
     * 					
     * 
     */
    @XmlEnumValue("Claim")
    CLAIM("Claim"),

    /**
     * This resource provides the adjudication details
     * 						from the processing of a Claim resource.
     * 					
     * 
     */
    @XmlEnumValue("ClaimResponse")
    CLAIM_RESPONSE("ClaimResponse"),

    /**
     * A record of a clinical assessment performed to
     * 						determine what problem(s) may affect the patient and before
     * 						planning the treatments or management strategies that are best to
     * 						manage a patient's condition. Assessments are often 1:1 with a
     * 						clinical consultation / encounter, but this varies greatly
     * 						depending on the clinical workflow. This resource is called
     * 						"ClinicalImpression" rather than
     * 						"ClinicalAssessment" to avoid confusion with the
     * 						recording of assessment tools such as Apgar score.
     * 					
     * 
     */
    @XmlEnumValue("ClinicalImpression")
    CLINICAL_IMPRESSION("ClinicalImpression"),

    /**
     * An occurrence of information being transmitted.
     * 						E.g., an alert that was sent to a responsible provider, a public
     * 						health agency was notified about a reportable condition.
     * 					
     * 
     */
    @XmlEnumValue("Communication")
    COMMUNICATION("Communication"),

    /**
     * A request to convey information. E.g., the CDS
     * 						system proposes that an alert be sent to a responsible provider,
     * 						the CDS system proposes that the public health agency be notified
     * 						about a reportable condition.
     * 					
     * 
     */
    @XmlEnumValue("CommunicationRequest")
    COMMUNICATION_REQUEST("CommunicationRequest"),

    /**
     * A set of healthcare-related information that is
     * 						assembled together into a single logical document that provides a
     * 						single coherent statement of meaning, establishes its own context
     * 						and that has clinical attestation with regard to who is making the
     * 						statement.
     * 					
     * 
     */
    @XmlEnumValue("Composition")
    COMPOSITION("Composition"),

    /**
     * A statement of relationships from one set of
     * 						concepts to one or more other concepts - either code systems or
     * 						data elements, or classes in class models.
     * 					
     * 
     */
    @XmlEnumValue("ConceptMap")
    CONCEPT_MAP("ConceptMap"),

    /**
     * Use to record detailed information about
     * 						conditions, problems or diagnoses recognized by a clinician. There
     * 						are many uses including: recording a Diagnosis during an
     * 						Encounter; populating a problem List or a Summary Statement, such
     * 						as a Discharge Summary.
     * 					
     * 
     */
    @XmlEnumValue("Condition")
    CONDITION("Condition"),

    /**
     * A conformance statement is a set of requirements
     * 						for a desired implementation or a description of how a target
     * 						application fulfills those requirements in a particular
     * 						implementation.
     * 					
     * 
     */
    @XmlEnumValue("Conformance")
    CONFORMANCE("Conformance"),

    /**
     * A formal agreement between parties regarding the
     * 						conduct of business, exchange of information or other matters.
     * 					
     * 
     */
    @XmlEnumValue("Contract")
    CONTRACT("Contract"),

    /**
     * Indicates an actual or potential clinical issue
     * 						with or between one or more active or proposed clinical actions
     * 						for a patient. E.g. Drug-drug interaction, Ineffective treatment
     * 						frequency, Procedure-condition conflict, etc.
     * 					
     * 
     */
    @XmlEnumValue("Contraindication")
    CONTRAINDICATION("Contraindication"),

    /**
     * Financial instrument which may be used to pay for
     * 						or reimburse for health care products and services.
     * 					
     * 
     */
    @XmlEnumValue("Coverage")
    COVERAGE("Coverage"),

    /**
     * The formal description of a single piece of
     * 						information that can be gathered and reported.
     * 					
     * 
     */
    @XmlEnumValue("DataElement")
    DATA_ELEMENT("DataElement"),

    /**
     * This resource identifies an instance of a
     * 						manufactured thing that is used in the provision of healthcare
     * 						without being substantially changed through that activity. The
     * 						device may be a machine, an insert, a computer, an application,
     * 						etc. This includes durable (reusable) medical equipment as well as
     * 						disposable equipment used for diagnostic, treatment, and research
     * 						for healthcare and public health.
     * 					
     * 
     */
    @XmlEnumValue("Device")
    DEVICE("Device"),

    /**
     * Describes the characteristics, operational status
     * 						and capabilities of a medical-related component of a medical
     * 						device.
     * 					
     * 
     */
    @XmlEnumValue("DeviceComponent")
    DEVICE_COMPONENT("DeviceComponent"),

    /**
     * Describes a measurement, calculation or setting
     * 						capability of a medical device.
     * 					
     * 
     */
    @XmlEnumValue("DeviceMetric")
    DEVICE_METRIC("DeviceMetric"),

    /**
     * Represents a request for a patient to employ a
     * 						medical device. The device may be an implantable device, or an
     * 						external assistive device, such as a walker.
     * 					
     * 
     */
    @XmlEnumValue("DeviceUseRequest")
    DEVICE_USE_REQUEST("DeviceUseRequest"),

    /**
     * A record of a device being used by a patient
     * 						where the record is the result of a report from the patient or
     * 						another clinician.
     * 					
     * 
     */
    @XmlEnumValue("DeviceUseStatement")
    DEVICE_USE_STATEMENT("DeviceUseStatement"),

    /**
     * A record of a request for a diagnostic
     * 						investigation service to be performed.
     * 					
     * 
     */
    @XmlEnumValue("DiagnosticOrder")
    DIAGNOSTIC_ORDER("DiagnosticOrder"),

    /**
     * The findings and interpretation of diagnostic
     * 						tests performed on patients, groups of patients, devices, and
     * 						locations, and/or specimens derived from these. The report
     * 						includes clinical context such as requesting and provider
     * 						information, and some mix of atomic results, images, textual and
     * 						coded interpretation, and formatted representation of diagnostic
     * 						reports.
     * 					
     * 
     */
    @XmlEnumValue("DiagnosticReport")
    DIAGNOSTIC_REPORT("DiagnosticReport"),

    /**
     * A manifest that defines a set of documents.
     * 					
     * 
     */
    @XmlEnumValue("DocumentManifest")
    DOCUMENT_MANIFEST("DocumentManifest"),

    /**
     * A reference to a document.
     * 
     */
    @XmlEnumValue("DocumentReference")
    DOCUMENT_REFERENCE("DocumentReference"),

    /**
     * This resource provides the insurance eligibility
     * 						details from the insurer regarding a specified coverage and
     * 						optionally some class of service.
     * 					
     * 
     */
    @XmlEnumValue("EligibilityRequest")
    ELIGIBILITY_REQUEST("EligibilityRequest"),

    /**
     * This resource provides eligibility and plan
     * 						details from the processing of an Eligibility resource.
     * 					
     * 
     */
    @XmlEnumValue("EligibilityResponse")
    ELIGIBILITY_RESPONSE("EligibilityResponse"),

    /**
     * An interaction between a patient and healthcare
     * 						provider(s) for the purpose of providing healthcare service(s) or
     * 						assessing the health status of a patient.
     * 					
     * 
     */
    @XmlEnumValue("Encounter")
    ENCOUNTER("Encounter"),

    /**
     * This resource provides the insurance Enrollment
     * 						details to the insurer regarding a specified coverage.
     * 					
     * 
     */
    @XmlEnumValue("EnrollmentRequest")
    ENROLLMENT_REQUEST("EnrollmentRequest"),

    /**
     * This resource provides Enrollment and plan
     * 						details from the processing of an Enrollment resource.
     * 					
     * 
     */
    @XmlEnumValue("EnrollmentResponse")
    ENROLLMENT_RESPONSE("EnrollmentResponse"),

    /**
     * An association between a patient and an
     * 						organization / healthcare provider(s) during which time encounters
     * 						may occur. The managing organization assumes a level of
     * 						responsibility for the patient during this time.
     * 					
     * 
     */
    @XmlEnumValue("EpisodeOfCare")
    EPISODE_OF_CARE("EpisodeOfCare"),

    /**
     * This resource provides: the claim details;
     * 						adjudication details from the processing of a Claim; and
     * 						optionally account balance information, for informing the
     * 						subscriber of the benefits provided.
     * 					
     * 
     */
    @XmlEnumValue("ExplanationOfBenefit")
    EXPLANATION_OF_BENEFIT("ExplanationOfBenefit"),

    /**
     * Significant health events and conditions for a
     * 						person related to the patient relevant in the context of care for
     * 						the patient.
     * 					
     * 
     */
    @XmlEnumValue("FamilyMemberHistory")
    FAMILY_MEMBER_HISTORY("FamilyMemberHistory"),

    /**
     * Prospective warnings of potential issues when
     * 						providing care to the patient.
     * 					
     * 
     */
    @XmlEnumValue("Flag")
    FLAG("Flag"),

    /**
     * Describes the intended objective(s) of patient
     * 						care, for example, weight loss, restoring an activity of daily
     * 						living, etc.
     * 					
     * 
     */
    @XmlEnumValue("Goal")
    GOAL("Goal"),

    /**
     * Represents a defined collection of entities that
     * 						may be discussed or acted upon collectively but which are not
     * 						expected to act collectively and are not formally or legally
     * 						recognized. I.e. A collection of entities that isn't an
     * 						Organization.
     * 					
     * 
     */
    @XmlEnumValue("Group")
    GROUP("Group"),

    /**
     * The details of a Healthcare Service available at
     * 						a location.
     * 					
     * 
     */
    @XmlEnumValue("HealthcareService")
    HEALTHCARE_SERVICE("HealthcareService"),

    /**
     * A set of DICOM SOP Instances of a patient,
     * 						selected for some application purpose, e.g., quality assurance,
     * 						teaching, conference, consulting, etc. Objects selected can be
     * 						from different studies, but must be of the same patient.
     * 					
     * 
     */
    @XmlEnumValue("ImagingObjectSelection")
    IMAGING_OBJECT_SELECTION("ImagingObjectSelection"),

    /**
     * Representation of the content produced in a DICOM
     * 						imaging study. A study comprises a set of Series, each of which
     * 						includes a set of Service-Object Pair Instances (SOP Instances -
     * 						images or other data) acquired or produced in a common context. A
     * 						Series is of only one modality (e.g., X-ray, CT, MR, ultrasound),
     * 						but a Study may have multiple Series of different modalities.
     * 					
     * 
     */
    @XmlEnumValue("ImagingStudy")
    IMAGING_STUDY("ImagingStudy"),

    /**
     * Immunization event information.
     * 					
     * 
     */
    @XmlEnumValue("Immunization")
    IMMUNIZATION("Immunization"),

    /**
     * A patient's point-of-time immunization status and
     * 						recommendation with optional supporting justification.
     * 					
     * 
     */
    @XmlEnumValue("ImmunizationRecommendation")
    IMMUNIZATION_RECOMMENDATION("ImmunizationRecommendation"),

    /**
     * A set of information summarized from a list of
     * 						other resources.
     * 					
     * 
     */
    @XmlEnumValue("List")
    LIST("List"),

    /**
     * Details and position information for a physical
     * 						place where services are provided and resources and participants
     * 						may be stored, found, contained or accommodated.
     * 					
     * 
     */
    @XmlEnumValue("Location")
    LOCATION("Location"),

    /**
     * A photo, video, or audio recording acquired or
     * 						used in healthcare. The actual content may be inline or provided
     * 						by direct reference.
     * 					
     * 
     */
    @XmlEnumValue("Media")
    MEDIA("Media"),

    /**
     * Primarily used for identification and definition
     * 						of Medication, but also covers ingredients and packaging.
     * 					
     * 
     */
    @XmlEnumValue("Medication")
    MEDICATION("Medication"),

    /**
     * Describes the event of a patient consuming or
     * 						otherwise being administered a medication. This may be as simple
     * 						as swallowing a tablet or it may be a long running infusion.
     * 						Related resources tie this event to the authorizing prescription,
     * 						and the specific encounter between patient and health care
     * 						practitioner.
     * 					
     * 
     */
    @XmlEnumValue("MedicationAdministration")
    MEDICATION_ADMINISTRATION("MedicationAdministration"),

    /**
     * Dispensing a medication to a named patient. This
     * 						includes a description of the supply provided and the instructions
     * 						for administering the medication.
     * 					
     * 
     */
    @XmlEnumValue("MedicationDispense")
    MEDICATION_DISPENSE("MedicationDispense"),

    /**
     * An order for both supply of the medication and
     * 						the instructions for administration of the medicine to a patient.
     * 					
     * 
     */
    @XmlEnumValue("MedicationPrescription")
    MEDICATION_PRESCRIPTION("MedicationPrescription"),

    /**
     * A record of medication being taken by a patient,
     * 						or that the medication has been given to a patient where the
     * 						record is the result of a report from the patient or another
     * 						clinician.
     * 					
     * 
     */
    @XmlEnumValue("MedicationStatement")
    MEDICATION_STATEMENT("MedicationStatement"),

    /**
     * The header for a message exchange that is either
     * 						requesting or responding to an action. The Reference(s) that are
     * 						the subject of the action as well as other Information related to
     * 						the action are typically transmitted in a bundle in which the
     * 						MessageHeader resource instance is the first resource in the
     * 						bundle.
     * 					
     * 
     */
    @XmlEnumValue("MessageHeader")
    MESSAGE_HEADER("MessageHeader"),

    /**
     * A curated namespace that issues unique symbols
     * 						within that namespace for the identification of concepts, people,
     * 						devices, etc. Represents a "System" used within the
     * 						Identifier and Coding data types.
     * 					
     * 
     */
    @XmlEnumValue("NamingSystem")
    NAMING_SYSTEM("NamingSystem"),

    /**
     * A request to supply a diet, formula feeding
     * 						(enteral) or oral nutritional supplement to a patient/resident.
     * 					
     * 
     */
    @XmlEnumValue("NutritionOrder")
    NUTRITION_ORDER("NutritionOrder"),

    /**
     * Measurements and simple assertions made about a
     * 						patient, device or other subject.
     * 					
     * 
     */
    @XmlEnumValue("Observation")
    OBSERVATION("Observation"),

    /**
     * A formal computable definition of an operation
     * 						(on the RESTful interface) or a named query (using the search
     * 						interaction).
     * 					
     * 
     */
    @XmlEnumValue("OperationDefinition")
    OPERATION_DEFINITION("OperationDefinition"),

    /**
     * A collection of error, warning or information
     * 						messages that result from a system action.
     * 					
     * 
     */
    @XmlEnumValue("OperationOutcome")
    OPERATION_OUTCOME("OperationOutcome"),

    /**
     * A request to perform an action.
     * 					
     * 
     */
    @XmlEnumValue("Order")
    ORDER("Order"),

    /**
     * A response to an order.
     * 
     */
    @XmlEnumValue("OrderResponse")
    ORDER_RESPONSE("OrderResponse"),

    /**
     * A formally or informally recognized grouping of
     * 						people or organizations formed for the purpose of achieving some
     * 						form of collective action. Includes companies, institutions,
     * 						corporations, departments, community groups, healthcare practice
     * 						groups, etc.
     * 					
     * 
     */
    @XmlEnumValue("Organization")
    ORGANIZATION("Organization"),

    /**
     * Demographics and other administrative information
     * 						about an individual or animal receiving care or other
     * 						health-related services.
     * 					
     * 
     */
    @XmlEnumValue("Patient")
    PATIENT("Patient"),

    /**
     * This resource provides the status of the payment
     * 						for goods and services rendered, and the request and response
     * 						resource references.
     * 					
     * 
     */
    @XmlEnumValue("PaymentNotice")
    PAYMENT_NOTICE("PaymentNotice"),

    /**
     * This resource provides payment details and claim
     * 						references supporting a bulk payment.
     * 					
     * 
     */
    @XmlEnumValue("PaymentReconciliation")
    PAYMENT_RECONCILIATION("PaymentReconciliation"),

    /**
     * Demographics and administrative information about
     * 						a person independent of a specific health-related context.
     * 					
     * 
     */
    @XmlEnumValue("Person")
    PERSON("Person"),

    /**
     * A person who is directly or indirectly involved
     * 						in the provisioning of healthcare.
     * 					
     * 
     */
    @XmlEnumValue("Practitioner")
    PRACTITIONER("Practitioner"),

    /**
     * An action that is or was performed on a patient.
     * 						This can be a physical 'thing' like an operation, or less invasive
     * 						like counseling or hypnotherapy.
     * 					
     * 
     */
    @XmlEnumValue("Procedure")
    PROCEDURE("Procedure"),

    /**
     * A request for a procedure to be performed. May be
     * 						a proposal or an order.
     * 					
     * 
     */
    @XmlEnumValue("ProcedureRequest")
    PROCEDURE_REQUEST("ProcedureRequest"),

    /**
     * This resource provides the target, request and
     * 						response, and action details for an action to be performed by the
     * 						target on or about existing resources.
     * 					
     * 
     */
    @XmlEnumValue("ProcessRequest")
    PROCESS_REQUEST("ProcessRequest"),

    /**
     * This resource provides processing status, errors
     * 						and notes from the processing of a resource.
     * 					
     * 
     */
    @XmlEnumValue("ProcessResponse")
    PROCESS_RESPONSE("ProcessResponse"),

    /**
     * Provenance of a resource is a record that
     * 						describes entities and processes involved in producing and
     * 						delivering or otherwise influencing that resource. Provenance
     * 						provides a critical foundation for assessing authenticity,
     * 						enabling trust, and allowing reproducibility. Provenance
     * 						assertions are a form of contextual metadata and can themselves
     * 						become important records with their own provenance. Provenance
     * 						statement indicates clinical significance in terms of confidence
     * 						in authenticity, reliability, and trustworthiness, integrity, and
     * 						stage in lifecycle (e.g., Document Completion - has the artifact
     * 						been legally authenticated), all of which may impact Security,
     * 						Privacy, and Trust policies.
     * 					
     * 
     */
    @XmlEnumValue("Provenance")
    PROVENANCE("Provenance"),

    /**
     * A structured set of questions intended to guide
     * 						the collection of answers. The questions are ordered and grouped
     * 						into coherent subsets, corresponding to the structure of the
     * 						grouping of the underlying questions.
     * 					
     * 
     */
    @XmlEnumValue("Questionnaire")
    QUESTIONNAIRE("Questionnaire"),

    /**
     * A structured set of questions and their answers.
     * 						The questions are ordered and grouped into coherent subsets,
     * 						corresponding to the structure of the grouping of the underlying
     * 						questions.
     * 					
     * 
     */
    @XmlEnumValue("QuestionnaireAnswers")
    QUESTIONNAIRE_ANSWERS("QuestionnaireAnswers"),

    /**
     * Used to record and send details about a request
     * 						for referral service or transfer of a patient to the care of
     * 						another provider or provider organisation.
     * 					
     * 
     */
    @XmlEnumValue("ReferralRequest")
    REFERRAL_REQUEST("ReferralRequest"),

    /**
     * Information about a person that is involved in
     * 						the care for a patient, but who is not the target of healthcare,
     * 						nor has a formal responsibility in the care process.
     * 					
     * 
     */
    @XmlEnumValue("RelatedPerson")
    RELATED_PERSON("RelatedPerson"),

    /**
     * An assessment of the likely outcome(s) for a
     * 						patient or other subject as well as the likelihood of each
     * 						outcome.
     * 					
     * 
     */
    @XmlEnumValue("RiskAssessment")
    RISK_ASSESSMENT("RiskAssessment"),

    /**
     * A container for slot(s) of time that may be
     * 						available for booking appointments.
     * 					
     * 
     */
    @XmlEnumValue("Schedule")
    SCHEDULE("Schedule"),

    /**
     * A Search Parameter that defines a named search
     * 						item that can be used to search/filter on a resource.
     * 					
     * 
     */
    @XmlEnumValue("SearchParameter")
    SEARCH_PARAMETER("SearchParameter"),

    /**
     * A slot of time on a schedule that may be
     * 						available for booking appointments.
     * 					
     * 
     */
    @XmlEnumValue("Slot")
    SLOT("Slot"),

    /**
     * Sample for analysis.
     * 
     */
    @XmlEnumValue("Specimen")
    SPECIMEN("Specimen"),

    /**
     * A definition of a FHIR structure. This resource
     * 						is used to describe the underlying resources, data types defined
     * 						in FHIR, and also for describing extensions, and constraints on
     * 						resources and data types.
     * 					
     * 
     */
    @XmlEnumValue("StructureDefinition")
    STRUCTURE_DEFINITION("StructureDefinition"),

    /**
     * The subscription resource is used to define a
     * 						push based subscription from a server to another system. Once a
     * 						subscription is registered with the server, the server checks
     * 						every resource that is created or updated, and if the resource
     * 						matches the given criteria, it sends a message on the defined
     * 						"channel" so that another system is able to take an
     * 						appropriate action.
     * 					
     * 
     */
    @XmlEnumValue("Subscription")
    SUBSCRIPTION("Subscription"),

    /**
     * A homogeneous material with a definite
     * 						composition.
     * 					
     * 
     */
    @XmlEnumValue("Substance")
    SUBSTANCE("Substance"),

    /**
     * A supply - a request for something, and provision
     * 						of what is supplied.
     * 					
     * 
     */
    @XmlEnumValue("Supply")
    SUPPLY("Supply"),

    /**
     * Record of delivery of what is supply.
     * 					
     * 
     */
    @XmlEnumValue("SupplyDelivery")
    SUPPLY_DELIVERY("SupplyDelivery"),

    /**
     * A supply - a request for something.
     * 					
     * 
     */
    @XmlEnumValue("SupplyRequest")
    SUPPLY_REQUEST("SupplyRequest"),

    /**
     * A value set specifies a set of codes drawn from
     * 						one or more code systems.
     * 					
     * 
     */
    @XmlEnumValue("ValueSet")
    VALUE_SET("ValueSet"),

    /**
     * An authorization for the supply of glasses and/or
     * 						contact lenses to a patient.
     * 					
     * 
     */
    @XmlEnumValue("VisionPrescription")
    VISION_PRESCRIPTION("VisionPrescription");
    private final java.lang.String value;

    ResourceTypeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static ResourceTypeList fromValue(java.lang.String v) {
        for (ResourceTypeList c: ResourceTypeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
