//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.07 at 01:41:53 PM EDT 
//


package org.hl7.fhir;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpecialValues-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SpecialValues-list">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="true"/>
 *     &lt;enumeration value="false"/>
 *     &lt;enumeration value="trace"/>
 *     &lt;enumeration value="sufficient"/>
 *     &lt;enumeration value="withdrawn"/>
 *     &lt;enumeration value="nil-known"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SpecialValues-list")
@XmlEnum
public enum SpecialValuesList {


    /**
     * Boolean true
     * 
     */
    @XmlEnumValue("true")
    TRUE("true"),

    /**
     * Boolean false
     * 
     */
    @XmlEnumValue("false")
    FALSE("false"),

    /**
     * The content is greater than zero, but too small
     * 						to be quantified
     * 					
     * 
     */
    @XmlEnumValue("trace")
    TRACE("trace"),

    /**
     * The specific quantity is not known, but is known
     * 						to be non-zero and is not specified because it makes up the bulk
     * 						of the material
     * 					
     * 
     */
    @XmlEnumValue("sufficient")
    SUFFICIENT("sufficient"),

    /**
     * The value is no longer available
     * 					
     * 
     */
    @XmlEnumValue("withdrawn")
    WITHDRAWN("withdrawn"),

    /**
     * The are no known applicable values in this
     * 						context
     * 					
     * 
     */
    @XmlEnumValue("nil-known")
    NIL_KNOWN("nil-known");
    private final java.lang.String value;

    SpecialValuesList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static SpecialValuesList fromValue(java.lang.String v) {
        for (SpecialValuesList c: SpecialValuesList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
